
import java.sql.Date;  
import java.time.LocalDate;

/**
 * Candidature generated by hbm2java
 */
public class Candidature  implements java.io.Serializable {


     private Integer id;
     private Offer offer;
     private Worker worker;
     private Date realizationDate;
     private String state;

    public Candidature() {
    }

    public Candidature(Offer offer, Worker worker) {
       this.offer = offer;
       this.worker = worker;
       this.realizationDate = Date.valueOf(LocalDate.now());
       this.state = "Pending";
    }