package entities;
// Generated 14-feb-2023 11:28:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alert generated by hbm2java
 */
public class Alert  implements java.io.Serializable {


     private Integer id;
     private Label label;
     private Worker worker;
     private String name;
     private Set notifications = new HashSet(0);

    public Alert() {
    }

    public Alert(Label label, Worker worker, String name, Set notifications) {
       this.label = label;
       this.worker = worker;
       this.name = name;
       this.notifications = notifications;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Label getLabel() {
        return this.label;
    }
    
    public void setLabel(Label label) {
        this.label = label;
    }
    public Worker getWorker() {
        return this.worker;
    }
    
    public void setWorker(Worker worker) {
        this.worker = worker;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getNotifications() {
        return this.notifications;
    }
    
    public void setNotifications(Set notifications) {
        this.notifications = notifications;
    }




}


