package entities;
// Generated 15-nov-2023 18:41:52 by Hibernate Tools 4.3.1



/**
 * Alert generated by hbm2java
 */
public class Alert  implements java.io.Serializable {


     private Integer id;
     private Profile profile;

    public Alert() {
    }

    public Alert(Profile profile) {
       this.profile = profile;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }




}


