package entities;
// Generated 31-oct-2023 21:04:09 by Hibernate Tools 4.3.1

 
/**
 * Alert generated by hbm2java
 */
public class Alert  implements java.io.Serializable {


     private Integer id;
     private Profile profile;

    public Alert() {
    }

    public Alert(Profile profile) {
       this.profile = profile;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }

}


