package entities;
// Generated 25-oct-2022 14:37:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Businessman generated by hbm2java
 */
public class Businessman  implements java.io.Serializable {


     private Integer id;
     private User user; 

    public Businessman() {
    }

    public Businessman(User user ) {
       this.user = user; 
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    } 
 
}


