package entities;
// Generated 14-feb-2023 11:28:17 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Candidature generated by hbm2java
 */
public class Candidature  implements java.io.Serializable {


     private Integer id;
     private Offer offer;
     private Date realizationDate;
     private Set messages = new HashSet(0);

    public Candidature() {
    }

    public Candidature(Offer offer, Date realizationDate, Set messages) {
       this.offer = offer;
       this.realizationDate = realizationDate;
       this.messages = messages;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Offer getOffer() {
        return this.offer;
    }
    
    public void setOffer(Offer offer) {
        this.offer = offer;
    }
    public Date getRealizationDate() {
        return this.realizationDate;
    }
    
    public void setRealizationDate(Date realizationDate) {
        this.realizationDate = realizationDate;
    }
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }




}


