package entities;
// Generated 18-feb-2023 23:32:23 by Hibernate Tools 4.3.1


import java.sql.Date;  
import java.time.LocalDate;

/**
 * Candidature generated by hbm2java
 */
public class Candidature  implements java.io.Serializable {


     private Integer id;
     private Offer offer;
     private Worker worker;
     private Date realizationDate;
     private String state;

    public Candidature() {
    }

    public Candidature(Offer offer, Worker worker) {
       this.offer = offer;
       this.worker = worker;
       this.realizationDate = Date.valueOf(LocalDate.now());
       this.state = "Pending";
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Offer getOffer() {
        return this.offer;
    }
    
    public void setOffer(Offer offer) {
        this.offer = offer;
    }
    public Worker getWorker() {
        return this.worker;
    }
    
    public void setWorker(Worker worker) {
        this.worker = worker;
    }
    public Date getRealizationDate() {
        return this.realizationDate;
    }
    
    public void setRealizationDate(Date realizationDate) {
        this.realizationDate = realizationDate;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }




}


