package entities;
// Generated 14-feb-2023 11:28:17 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Knowledge generated by hbm2java
 */
public class Knowledge  implements java.io.Serializable {


     private Integer id;
     private Worker worker;
     private String name;
     private Date fechaInicio;
     private Date fechaFin; 

    public Knowledge() {
    }

    public Knowledge(Worker worker, String name, Date fechaInicio, Date fechaFin ) {
       this.worker = worker;
       this.name = name;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin; 
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Worker getWorker() {
        return this.worker;
    }
    
    public void setWorker(Worker worker) {
        this.worker = worker;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    } 



}


