package entities;
// Generated 14-feb-2023 11:28:17 by Hibernate Tools 4.3.1
 

/**
 * Label generated by hbm2java
 */
public class Label  implements java.io.Serializable {


     private Integer id;
     private String name; 

    public Label() {
    }

    public Label(String name ) {
       this.name = name; 
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    } 

}


