package entities;
// Generated 18-feb-2023 23:32:23 by Hibernate Tools 4.3.1



/**
 * LabelOffer generated by hbm2java
 */
public class LabelOffer  implements java.io.Serializable {


     private Integer id;
     private Label label;
     private Offer offer;

    public LabelOffer() {
    }

    public LabelOffer(Label label, Offer offer) {
       this.label = label;
       this.offer = offer;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Label getLabel() {
        return this.label;
    }
    
    public void setLabel(Label label) {
        this.label = label;
    }
    public Offer getOffer() {
        return this.offer;
    }
    
    public void setOffer(Offer offer) {
        this.offer = offer;
    }




}


