package entities;
// Generated 25-oct-2022 14:37:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Label generated by hbm2java
 */
public class Label  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set labelOferts = new HashSet(0);

    public Label() {
    }

    public Label(String name, Set labelOferts) {
       this.name = name;
       this.labelOferts = labelOferts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getLabelOferts() {
        return this.labelOferts;
    }
    
    public void setLabelOferts(Set labelOferts) {
        this.labelOferts = labelOferts;
    }




}


