package entities;
// Generated 25-oct-2022 14:37:38 by Hibernate Tools 4.3.1



/**
 * LabelOfert generated by hbm2java
 */
public class LabelOfert  implements java.io.Serializable {


     private Integer id;
     private Label label;
     private Ofert ofert;

    public LabelOfert() {
    }

    public LabelOfert(Label label, Ofert ofert) {
       this.label = label;
       this.ofert = ofert;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Label getLabel() {
        return this.label;
    }
    
    public void setLabel(Label label) {
        this.label = label;
    }
    public Ofert getOfert() {
        return this.ofert;
    }
    
    public void setOfert(Ofert ofert) {
        this.ofert = ofert;
    }




}


