package entities;
// Generated 15-nov-2023 18:41:52 by Hibernate Tools 4.3.1
 
import java.sql.Timestamp;
import java.time.LocalDateTime; 


/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


    private Integer id;
    private Candidature candidature;
    private User user;
    private String content;
    private Timestamp sendedTime;
     
    public Message() {
    }

    public Message(Candidature candidature, User user, String content) {
       this.candidature = candidature;
       this.user = user;
       this.content = content;
       this.sendedTime = Timestamp.valueOf(LocalDateTime.now());
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Candidature getCandidature() {
        return this.candidature;
    }
    
    public void setCandidature(Candidature candidature) {
        this.candidature = candidature;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    public Timestamp getSendedTime() {
        return sendedTime;
    }

    public void setSendedTime(Timestamp sendedTime) {
        this.sendedTime = sendedTime;
    } 
}


