package entities;
// Generated 31-oct-2023 21:04:09 by Hibernate Tools 4.3.1



/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer id;
     private Candidature candidature;
     private String content;
     private Boolean sender;

    public Message() {
    }

    public Message(Candidature candidature, String content, Boolean sender) {
       this.candidature = candidature;
       this.content = content;
       this.sender = sender;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Candidature getCandidature() {
        return this.candidature;
    }
    
    public void setCandidature(Candidature candidature) {
        this.candidature = candidature;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Boolean getSender() {
        return this.sender;
    }
    
    public void setSender(Boolean sender) {
        this.sender = sender;
    }




}


