package entities;
// Generated 15-nov-2023 18:41:52 by Hibernate Tools 4.3.1



/**
 * NewMessageNotification generated by hbm2java
 */
public class NewMessageNotification  implements java.io.Serializable {


     private Integer id;
     private Message message;
     private Notification notification;

    public NewMessageNotification() {
    }

    public NewMessageNotification(Message message, Notification notification) {
       this.message = message;
       this.notification = notification;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Message getMessage() {
        return this.message;
    }
    
    public void setMessage(Message message) {
        this.message = message;
    }
    public Notification getNotification() {
        return this.notification;
    }
    
    public void setNotification(Notification notification) {
        this.notification = notification;
    }




}


