package entities;
// Generated 15-nov-2023 18:41:52 by Hibernate Tools 4.3.1



/**
 * NewOfferNotification generated by hbm2java
 */
public class NewOfferNotification  implements java.io.Serializable {


     private Integer id;
     private Alert alert;
     private Notification notification;
     private Offer offer;

    public NewOfferNotification() {
    }

    public NewOfferNotification(Alert alert, Notification notification, Offer offer) {
       this.alert = alert;
       this.notification = notification;
       this.offer = offer;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Alert getAlert() {
        return this.alert;
    }
    
    public void setAlert(Alert alert) {
        this.alert = alert;
    }
    public Notification getNotification() {
        return this.notification;
    }
    
    public void setNotification(Notification notification) {
        this.notification = notification;
    }
    public Offer getOffer() {
        return this.offer;
    }
    
    public void setOffer(Offer offer) {
        this.offer = offer;
    }




}


