package entities;
// Generated 18-feb-2023 23:32:23 by Hibernate Tools 4.3.1



/**
 * Notification generated by hbm2java
 */
public class Notification  implements java.io.Serializable {


     private Integer id;
     private Alert alert;
     private Label label;
     private Offer offer;
     private Boolean notified;

    public Notification() {
    }

    public Notification(Alert alert, Label label, Offer offer, Boolean notified) {
       this.alert = alert;
       this.label = label;
       this.offer = offer;
       this.notified = notified;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Alert getAlert() {
        return this.alert;
    }
    
    public void setAlert(Alert alert) {
        this.alert = alert;
    }
    public Label getLabel() {
        return this.label;
    }
    
    public void setLabel(Label label) {
        this.label = label;
    }
    public Offer getOffer() {
        return this.offer;
    }
    
    public void setOffer(Offer offer) {
        this.offer = offer;
    }
    public Boolean getNotified() {
        return this.notified;
    }
    
    public void setNotified(Boolean notified) {
        this.notified = notified;
    }




}


