package entities;
// Generated 15-nov-2023 18:41:52 by Hibernate Tools 4.3.1



/**
 * Notification generated by hbm2java
 */
public class Notification  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Boolean notified;

    public Notification() {
    }

    public Notification(User user) {
       this.user = user;
       this.notified = false;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Boolean getNotified() {
        return this.notified;
    }
    
    public void setNotified(Boolean notified) {
        this.notified = notified;
    }




}


