package entities;
// Generated 14-feb-2023 11:28:17 by Hibernate Tools 4.3.1



/**
 * Notification generated by hbm2java
 */
public class Notification  implements java.io.Serializable {


     private Integer id;
     private Alert alert;
     private Label label;
     private Offer offer;

    public Notification() {
    }

    public Notification(Alert alert, Label label, Offer offer) {
       this.alert = alert;
       this.label = label;
       this.offer = offer;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Alert getAlert() {
        return this.alert;
    }
    
    public void setAlert(Alert alert) {
        this.alert = alert;
    }
    public Label getLabel() {
        return this.label;
    }
    
    public void setLabel(Label label) {
        this.label = label;
    }
    public Offer getOffer() {
        return this.offer;
    }
    
    public void setOffer(Offer offer) {
        this.offer = offer;
    }




}


