package entities;
// Generated 31-oct-2023 21:04:09 by Hibernate Tools 4.3.1

 

/**
 * Profile generated by hbm2java
 */
public class Profile  implements java.io.Serializable { 

     private Integer id;
     private Worker worker;
     private String name; 

    public Profile() {
    }

    public Profile(Worker worker, String name) {
       this.worker = worker;
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Worker getWorker() {
        return this.worker;
    }
    
    public void setWorker(Worker worker) {
        this.worker = worker;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

}


