package entities;
// Generated 31-oct-2023 21:04:09 by Hibernate Tools 4.3.1



/**
 * ProfileLabel generated by hbm2java
 */
public class ProfileLabel  implements java.io.Serializable {


     private Integer id;
     private Label label;
     private Profile profile;

    public ProfileLabel() {
    }

    public ProfileLabel(Label label, Profile profile) {
       this.label = label;
       this.profile = profile;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Label getLabel() {
        return this.label;
    }
    
    public void setLabel(Label label) {
        this.label = label;
    }
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }




}


