package entities;
// Generated 15-nov-2023 18:41:52 by Hibernate Tools 4.3.1



/**
 * Profile generated by hbm2java
 */
public class Profile  implements java.io.Serializable {


     private Integer id;
     private Worker worker;
     private String name;

    public Profile() {
    }

    public Profile(Worker worker, String name) {
       this.worker = worker;
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Worker getWorker() {
        return this.worker;
    }
    
    public void setWorker(Worker worker) {
        this.worker = worker;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


