package entities;
// Generated 14-feb-2023 11:28:17 by Hibernate Tools 4.3.1



/**
 * Qualification generated by hbm2java
 */
public class Qualification  implements java.io.Serializable {


     private Integer id;
     private Knowledge knowledge;
     private String qualificationName;
     private String studyCenter;

    public Qualification() {
    }

    public Qualification(Knowledge knowledge, String qualificationName, String studyCenter) {
       this.knowledge = knowledge;
       this.qualificationName = qualificationName;
       this.studyCenter = studyCenter;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Knowledge getKnowledge() {
        return this.knowledge;
    }
    
    public void setKnowledge(Knowledge knowledge) {
        this.knowledge = knowledge;
    }
    public String getQualificationName() {
        return this.qualificationName;
    }
    
    public void setQualificationName(String qualificationName) {
        this.qualificationName = qualificationName;
    }
    public String getStudyCenter() {
        return this.studyCenter;
    }
    
    public void setStudyCenter(String studyCenter) {
        this.studyCenter = studyCenter;
    }




}


