package entities;
// Generated 15-nov-2023 18:41:52 by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String dni;
     private String name;
     private String surname;
     private String email;
     private String user;
     private String password;

    public User() {
    }

    public User(String dni, String name, String surname, String email, String user, String password) {
       this.dni = dni;
       this.name = name;
       this.surname = surname;
       this.email = email;
       this.user = user;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString(){
        return this.getName()+" "+this.getSurname();
    }
    
    @Override
    public boolean equals(Object object){
        User other = (User) object;
        if(!this.getDni().equals(other.getDni()))
            return false;
        
        if(!this.getEmail().equals(other.getEmail()))
            return false;
        
        if(!this.getName().equals(other.getName()))
            return false;
        
        if(!this.getSurname().equals(other.getSurname()))
            return false;
        
        if(!this.getUser().equals(other.getUser()))
            return false;
        if(!this.getPassword().equals(other.getPassword()))
            return false;
        
        return true;
    }  
}


