package entities; 
// Generated 25-oct-2022 14:37:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String dni;
     private String name;
     private String surname;
     private String email;
     private String user;
     private String password; 

    public User() {
    }

	
    public User(String dni) {
        this.dni = dni;
    }
    public User(String dni, String name, String surname, String email, String user, String password) {
       this.dni = dni;
       this.name = name;
       this.surname = surname;
       this.email = email;
       this.user = user;
       this.password = password; 
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    } 

}


