package entities;
// Generated 31-oct-2023 21:04:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Worker generated by hbm2java
 */
public class Worker  implements java.io.Serializable {


     private Integer id;
     private User user; 

    public Worker() {
    }

    public Worker(User user) {
       this.user = user;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }


}


