package entities;
// Generated 15-nov-2023 18:41:52 by Hibernate Tools 4.3.1



/**
 * Worker generated by hbm2java
 */
public class Worker  implements java.io.Serializable {


     private Integer id;
     private User user;

    public Worker() {
    }

    public Worker(User user) {
       this.user = user;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


